= セットアップ
include::_attributes.adoc[]

== OpenShift クラスターのセットアップ
:profile: acs

OpenShift4 を実行するには、 https://demo.redhat.com[RHPDS] を使用してプロビジョニングされた環境が 1 つ必要です。
カタログ → Openshift 4.10 ワークショップ → Order を実行します。

== OpenShift Web コンソールのログイン

ワークショップ環境が整ったら、OpenShift Web コンソールにもアクセスできます。 +
Web コンソールの URL は、RHPDS とクラスター管理者のユーザー名/パスワードに表示されます。

NOTE: 言語設定が「英語」に設定されていない場合は、ユーザー設定メニューで「英語」に設定するとよい場合があります。  +
「英語」に設定せずにこのワークショップを続行すると、DevSecOps ラボでパイプラインが正しく表示されません。

== 踏み台サーバーに接続する

また、SSH 経由で環境内の踏み台サーバーにアクセスする必要があります。

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
ssh lab-user@<YOUR_BASTION_SERVER>
----

一部の CLI ツールは、踏み台サーバーに既にインストールされています。以下を使用して OpenShift のバージョンを確認できます。

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
oc version	
----

出力には oc バージョン >=4.10 が表示されます。

[.console-output]
[source,bash,subs="attributes+,+macros"]	
----	
Client Version: {ocp-version}
Server Version: {ocp-version}
Kubernetes Version: {kubernetes-version}
----

== デフォルトのプロジェクト テンプレートを編集する

次に、まず、デフォルトのプロジェクト テンプレートを編集する必要があります。
RHPDS が提供する Openshift 4.10 Workshop 環境では、新しく作成されたプロジェクトに対して制限範囲(Limit Ranges)が自動的に設定されます。これは、ワークショップの円滑な運営を妨げる可能性があります。

`oc edit` コマンドを使用して、Limit Range セクションを<ins>**削除**</ins>します。

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
oc edit template project-request -n openshift-config
----

`project-request` マニフェストから次の部分をすべて削除して保存します。

----
- apiVersion: v1
  kind: LimitRange
  metadata:
    name: ${PROJECT_NAME}-core-resource-limits
    namespace: ${PROJECT_NAME}
  spec:
    limits:
    - default:
        cpu: 500m
        memory: 1.5Gi
      defaultRequest:
        cpu: 50m
        memory: 256Mi
      max:
        cpu: 4
        memory: 6Gi
      type: Container
    - max:
        cpu: 4
        memory: 12Gi
      type: Pod
----

== チュートリアルのソースを入手する

:tutorial-url: https://github.com/RH-OPEN/acs-workshop.git
:folder: acs-workshop
include::https://raw.githubusercontent.com/redhat-developer-demos/rhd-tutorial-common/master/download-sources.adoc[]


これで、Openshift に RHACS をインストールする準備が整いました。
